name: 'builder'
description: ''
inputs:
  dry-run:
    description: 'do not publish anything'
    required: false
    default: false
  token:
    description: 'github token'
    required: true
runs:
  using: 'node12'
  main: '../../dist/builder/index.js'
